# Generated by Django 3.1.6 on 2021-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='photo',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
